__COMMiTs [7/29 - 2:39PM]__ ---- - minor readme fix & update - added BACKUP folder & slxrmeV0.1-bp.py - added paste.md and inserted old script tat may be useful in future use - mnior prvivreme fix & update
__Needs TO BE DONE__
----
- fix indentaion & code on "SLXRme-v0.0.1.py"
- watch & research proper indentation and code setup
- work more on "SLACHE Bank"
- debug "SLxREmeV0.0.1.py"

__KEY INFO & COMMENTS__
----
- "SLxREmeV0.0.1.py" may be written wrong. The code is read by python until it gets to Line #71 and then it stops. It Jumps somewhere else, such as an else statement. Still have not determined why it does this or which statement itself it goes to.
- "SLVCHE BANK" is not yet done. When running program in terminal it says "/usr/local/bin/python3: can't open file '/Users/usa/Documents/TERMiNAL Xi/KODE/PiTHON/PVSS-ME/TERMiNAL/SLACHE-BANK.py/usr/local/bin/python3': [Errno 20] Not a directory". This is because the path is not correct. It should be "/usr/local/bin/python3". *Must Find a Way to Fix This* (I have tried to fix it but it still doesn't work).
- "SLxRmeV0.0.2.py" is returns this in terminal when ran; "Traceback (most recent call last):
File "/Users/usa/Documents/TERMiNAL Xi/KODE/PiTHON/PVSS-ME/TERMiNAL/SLxRme-v0.0.2.py", line 54, in <module>
if iteration == total:
NameError: name 'iteration' is not... *Find a Way to Fix This*